
package com.mpersd.soap.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-11-21T12:37:31.295-06:00
 * Generated source version: 3.1.6
 * 
 */
public final class ConversionWS_ConversionWSImpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.soap.mpersd.com/", "ConversionWSImpService");

    private ConversionWS_ConversionWSImpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConversionWSImpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConversionWSImpService ss = new ConversionWSImpService(wsdlURL, SERVICE_NAME);
        ConversionWS port = ss.getConversionWSImpPort();  
        
        {
        System.out.println("Invoking getTipoCambio...");
        java.lang.String _getTipoCambio_arg0 = "";
        com.mpersd.soap.webservice.Moneda _getTipoCambio__return = port.getTipoCambio(_getTipoCambio_arg0);
        System.out.println("getTipoCambio.result=" + _getTipoCambio__return);


        }
        {
        System.out.println("Invoking pesoADolar...");
        java.lang.Double _pesoADolar_arg0 = null;
        java.lang.Double _pesoADolar__return = port.pesoADolar(_pesoADolar_arg0);
        System.out.println("pesoADolar.result=" + _pesoADolar__return);


        }
        {
        System.out.println("Invoking dolarAPeso...");
        java.lang.Double _dolarAPeso_arg0 = null;
        java.lang.Double _dolarAPeso__return = port.dolarAPeso(_dolarAPeso_arg0);
        System.out.println("dolarAPeso.result=" + _dolarAPeso__return);


        }

        System.exit(0);
    }

}
